### ISSUE TITLE
FYI: hiera5 Implementation

### ISSUE THREAD

**Issue by NITEMAN** [ribbybibby/terraform-provider-hiera#1]
We have developed an hiera5 implementation based on lyra's  hiera in golang API: https://gitlab.com/sbitio/terraform-provider-hiera5

**Comment by ribbybibby** [comment]
Glad to see that someone got around to implementing this! I've updated the README to point at your project: https://github.com/ribbybibby/terraform-provider-hiera/commit/721c4d1decede7ac69cdd84815fb94f24ccb8ba6.

It seems odd that this project which only supports the deprecated v3 has the distinction of the name `hiera` while yours, which supports the current version, has to prepend the version number. It would make more sense the other way around.

**Comment by NITEMAN** [comment]
Thanks for the pointer ;)

Doesn't mind about version in provider name it's perfectly ok since v3 and v5 are incompatible and the later comes after.
